p8105_hw2_sm5975
================
Sania Sheifuddin
2026-10-07

Read and clean the data; retain line, station, name, station latitude /
longitude, routes served, entry, vending, entrance type, and ADA
compliance. Convert the entry variable from character (YES vs NO) to a
logical variable (case_match function may be useful).

Write a short paragraph about this dataset – explain briefly what
variables the dataset contains, describe your data cleaning steps so
far, and give the dimension (rows x columns) of the resulting dataset.
Are these data tidy?

# Question 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
nyctransit_df = 
    read_csv(
      "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv", 
      na = c("NA", ".", ""), 
col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c"))

nyctransit_df =
  nyctransit_df |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude,
    route1:route11, entry, vending, entrance_type, ada
  ) |>
  mutate(entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE))
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

This dataset consists of information on each entrance and exit of NYC
subway situations. Variables included are the following: station name,
station latitude/longitude, routes served, subway line, whether the
entrance allows entry, if there is vending, the entrance types and ADA
compliance.

To clean the data further I standardized the variable names to only have
the variables of interest. I also converted entry from a character
variable to a logical variable. After I ran the chunk I observed that
the final dataset has 1868 rows and 19 columns. Since route information
is from route 1 through route 11 the route number is stored in the
column names.

``` r
nyctransit_df |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

From the dataset we can see that, there are 465 distinct stations.

``` r
nyctransit_df |>
  filter(ada) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

From the dataset we can see that there are 84 ADA compliant stations.

``` r
nyctransit_df |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

    ## [1] 0.3770492

The proportion of entrances/exits without vending that allow entry is
0.377.

``` r
#Reformatting data so that route number and route name are distinct variables
nyctransit_tidy_df =nyctransit_df |>
  mutate(across(route8:route11, as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name",
    names_prefix = "route",
    values_drop_na = TRUE
  )

# Distinct stations that serve the A train
nyctransit_tidy_df |>
  filter(route_name == "A") |>
  distinct(station_name, line) |>
  nrow()
```

    ## [1] 60

``` r
# A train stations that are ADA compliant
nyctransit_tidy_df |>
  filter(route_name == "A", ada) |>
  distinct(station_name, line) |>
  nrow()
```

    ## [1] 17

From the dataset provided we can see that, 60 distinct stations serve
the A train.

Of the stations that serve the A train, 17 are ADA compliant.

# Question 2

``` r
#Read and Clean Mr. Trash Wheel sheet

library(readxl)
mrtrash_wheel_df =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  ) |>
  janitor::clean_names() |> 
 drop_na(dumpster) |>
  mutate(sports_balls = as.integer(round(sports_balls)))
```

``` r
#Combining with Mr. Trash Wheel Dataset to produce a single tidy dataset
library(tidyverse)
library(readxl)

mrtrash_wheel_df = 
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  ) |>
  janitor::clean_names() |> 
 drop_na(dumpster) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
         year = as.integer (year),
         month = str_trim(month),
         trash_wheel = "Mr. Trash Wheel"
  )

proftrash_wheel_df =
  read_excel(
    "data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139",
    col_types = c(
      "numeric", "text", "numeric", "date", "numeric", "numeric",
      "numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
      "numeric"
    )
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.integer(year),
    month = str_trim(month),
    trash_wheel = "Professor Trash Wheel"
  )
```

    ## Warning: Expecting numeric in G137 / R137C7: got 'dive'

``` r
gwynndatr_df = 
  read_excel(
     "data/202610 Trash Wheel Collection Data.xlsx",
     sheet = "Gwynnda the Good Wheel of the W",
     range = "A2:L394"
  ) |> 
  janitor::clean_names() |> 
  drop_na(dumpster) |> 
  mutate(
    year = as.integer(year),
    month = str_trim(month),
    trash_wheel = "Gwynnda"
  )

trash_wheel_df = 
  bind_rows (mrtrash_wheel_df, proftrash_wheel_df, gwynndatr_df) |> 
  relocate (trash_wheel)
```

``` r
 # the total weight of trash collected by Professor Trash Wheel
prof_totalweight =
  trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  pull(weight_tons) |>
  sum(na.rm = TRUE)

#the total number of cigarette butts collected by Gwynnda in June of 2022
gwynnda_2022cigg =
  trash_wheel_df |>
  filter(trash_wheel == "Gwynnda", month == "June", year == 2022) |>
  pull(cigarette_butts) |>
  sum(na.rm = TRUE)
```

The final combined dataset, `trash_wheel_df`, contains 1269
observations, where each observation is a single dumpster collection by
Mr. Trash Wheel, Professor Trash Wheel, or Gwynnda, with 15 variables.
The data span 2014 to 2026. Key variables include `trash_wheel` (which
wheel collected the trash), `dumpster` (the dumpster number), `month`,
`year`, and `date`, along with `weight_tons` and `volume_cubic_yards`,
and counts of specific items such as `plastic_bottles`,
`cigarette_butts`, `wrappers`, and `homes_powered`. The variable
`sports_balls` is available only for Mr. Trash Wheel, and
`glass_bottles` is not recorded for Gwynnda, so those values are `NA` in
the combined data. For available data, Professor Trash Wheel collected a
total of 294.96 tons of trash. Gwynnda collected a total of 18,120
cigarette butts in June of 2022.
